# Generated by Django 4.2.4 on 2023-08-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netcores', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
    ]
