# Generated by Django 4.2.4 on 2023-08-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netcores', '0004_rename_client_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
