# Generated by Django 4.2.4 on 2023-08-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netcores', '0006_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('handle_by', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=244)),
                ('account_number', models.BigIntegerField()),
                ('ifsc_code', models.CharField(max_length=250)),
                ('bank_name', models.CharField(max_length=250)),
                ('gst_number', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netcores.client')),
            ],
        ),
    ]
