# Generated by Django 4.2.4 on 2023-08-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netcores', '0007_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netcores.client'),
        ),
    ]
