# Generated by Django 4.2.4 on 2023-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcores', '0008_alter_company_account_number_alter_company_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
